### ISSUE TITLE
Issue with Kirby 2.4.1 ?

### ISSUE THREAD

**Issue by m-artin** [fishme/kirby_ckeditor#2]
Couldn't make it run properly with latest Kirby version 2.4.1
Maybe I've overlooked something? 

1. Copied the folder to site/fields/ckeditor
2. Called the field via the blueprint with 'ckeditor'
3. Commented out line 31 in the .htaccess for my test run 
   #RewriteRule ^site/(.*) index.php [L]

Browser-inspector throws this error in the js console: 
[Error] http://localhost:8888//install/site/fields/ckeditor/assets/js/ckeditor.js 
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by fishme** [comment]
I tried it with 2.4.1 and it works fine.
If I have a look to your path, then I see you have the installation mode on. please go to your /site/config/config.php and remove the config line with panel.install.

then it should works.

I also updated the code, so let me know if something is not working.

**Comment by m-artin** [comment]
Thanks a lot!

I've also figured out the issue was related to `$_SERVER['HTTP_REFERER']` on line 50.
Which inserted a path from the page visited before in the browser. In my first test run this was the install page and in my second run, the login page.

**Comment by fishme** [comment]
yeah, that I fixed also with the last patch. ;)

**Comment by m-artin** [comment]
Great! I saw that.
