### ISSUE TITLE
Any plans for this to be updated for latest Kirby?

### ISSUE THREAD

**Issue by seffw** [fishme/kirby_ckeditor#6]
Nice idea. Not working on latest Kirby (no editor on textarea field, just the blank field with text).

Tried various permissions on field folders jjust in case, though I'm presuming this is down to being built for an older Kirby version.

**Comment by seffw** [comment]
Mistake. Reviewd permissions again, changed and now working fine

**Comment by fishme** [comment]
Good :-) enjoy
